"""Storage interface. The service layer depends only on this protocol."""

from __future__ import annotations

from contextlib import AbstractContextManager
from datetime import datetime
from typing import Protocol

from .models import Claim, Household, Item, Notice, NoticeKind, Person, User


class Repository(Protocol):
    def write(self) -> AbstractContextManager[None]:
        """Serialised write transaction; reads inside it see a stable state."""
        ...

    # users
    def add_user(self, google_sub: str, email: str, name: str, at: datetime) -> User: ...
    def user(self, user_id: int) -> User | None: ...
    def user_by_sub(self, google_sub: str) -> User | None: ...
    def all_users(self) -> list[User]: ...
    def touch_user(self, user_id: int, at: datetime) -> None: ...
    def start_visit(self, user_id: int) -> None: ...
    def reset_visits_since_claim(self, user_id: int) -> None: ...
    def set_gerry(self, user_id: int, ghost: bool, last_line: str | None) -> None: ...
    def delete_user(self, user_id: int) -> None: ...

    # households
    def add_household(self, name: str, invite_token: str) -> Household: ...
    def household(self, household_id: int) -> Household | None: ...
    def household_by_invite(self, invite_token: str) -> Household | None: ...
    def all_households(self) -> list[Household]: ...
    def rename_household(self, household_id: int, name: str) -> None: ...
    def delete_household(self, household_id: int) -> None: ...

    # people
    def add_person(self, household_id: int, name: str, user_id: int | None) -> Person: ...
    def person(self, person_id: int) -> Person | None: ...
    def person_for_user(self, user_id: int) -> Person | None: ...
    def people_in_household(self, household_id: int) -> list[Person]: ...
    def rename_person(self, person_id: int, name: str) -> None: ...
    def move_person(self, person_id: int, household_id: int) -> None: ...
    def delete_person(self, person_id: int) -> None: ...

    # items
    def add_item(self, person_id: int, title: str, url: str | None, image: str | None,
                 price_minor: int, note: str | None, really_want: bool, at: datetime) -> Item: ...
    def item(self, item_id: int) -> Item | None: ...
    def items_for_person(self, person_id: int) -> list[Item]: ...  # ordered by position
    def update_item(self, item_id: int, title: str, url: str | None, image: str | None,
                    price_minor: int, note: str | None, really_want: bool) -> None: ...
    def set_positions(self, ordered_item_ids: list[int]) -> None: ...
    def set_bought(self, item_id: int, at: datetime | None) -> None: ...
    def delete_item(self, item_id: int) -> None: ...
    def delete_all_items(self) -> None: ...

    # claims
    def claims_for_item(self, item_id: int) -> list[Claim]: ...
    def claims_by_user(self, user_id: int) -> list[Claim]: ...
    def add_claim(self, item_id: int, user_id: int, amount_minor: int, at: datetime) -> None: ...
    def set_claim_amount(self, item_id: int, user_id: int, amount_minor: int) -> None: ...
    def delete_claim(self, item_id: int, user_id: int) -> None: ...

    # notices
    def add_notice(self, user_id: int, kind: NoticeKind, params: dict, at: datetime) -> None: ...
    def notices_for_user(self, user_id: int) -> list[Notice]: ...
    def delete_notice(self, notice_id: int, user_id: int) -> None: ...
    def delete_all_notices(self) -> None: ...

    # settings
    def setting(self, key: str) -> str | None: ...
    def set_setting(self, key: str, value: str) -> None: ...
