"""Storage interface. The service layer depends only on this protocol."""

from __future__ import annotations

from contextlib import AbstractContextManager
from datetime import datetime
from typing import Protocol

from .models import Activity, ActivityKind, Claim, Household, Item, Notice, NoticeKind, Person, User


class Repository(Protocol):
    def write(self) -> AbstractContextManager[None]:
        """Serialised write transaction; reads inside it see a stable state."""
        ...

    # users
    def add_user(self, google_sub: str, email: str, name: str, at: datetime) -> User: ...
    def user(self, user_id: int) -> User | None: ...
    def user_by_sub(self, google_sub: str) -> User | None: ...
    def all_users(self) -> list[User]: ...
    def touch_user(self, user_id: int, at: datetime) -> None: ...
    def start_visit(self, user_id: int) -> None: ...
    def reset_visits_since_claim(self, user_id: int) -> None: ...
    def reset_all_visits_since_claim(self) -> None: ...
    def set_gerry(self, user_id: int, ghost: bool, last_line: str | None) -> None: ...
    def delete_user(self, user_id: int) -> None: ...
    def rename_user(self, user_id: int, name: str) -> None: ...
    def user_by_magic_token(self, token: str) -> User | None: ...
    def set_magic_token(self, user_id: int, token: str) -> None: ...  # upsert; also used to regenerate
    def magic_token_for_user(self, user_id: int) -> str | None: ...
    def set_punishment_mode(self, user_id: int, enabled: bool) -> None: ...
    def set_email_subscription(self, user_id: int, subscribed: bool, timezone: str | None) -> None: ...
    def set_last_digest_sent(self, user_id: int, date_iso: str) -> None: ...
    def subscribed_users(self) -> list[User]: ...

    # households
    def add_household(self, name: str, invite_token: str) -> Household: ...
    def household(self, household_id: int) -> Household | None: ...
    def household_by_invite(self, invite_token: str) -> Household | None: ...
    def all_households(self) -> list[Household]: ...
    def rename_household(self, household_id: int, name: str) -> None: ...
    def delete_household(self, household_id: int) -> None: ...

    # people
    def add_person(self, household_id: int, name: str, user_id: int | None) -> Person: ...
    def person(self, person_id: int) -> Person | None: ...
    def person_for_user(self, user_id: int) -> Person | None: ...
    def people_in_household(self, household_id: int) -> list[Person]: ...
    def rename_person(self, person_id: int, name: str) -> None: ...
    def move_person(self, person_id: int, household_id: int) -> None: ...
    def delete_person(self, person_id: int) -> None: ...
    def dependents_count_by_household(self) -> list[tuple[int, int]]: ...  # (household_id, count)

    # items
    def add_item(self, person_id: int, title: str, url: str | None, image: str | None,
                 price_minor: int, note: str | None, really_want: bool, at: datetime,
                 is_voucher: bool = False) -> Item: ...
    def item(self, item_id: int) -> Item | None: ...
    def items_for_person(self, person_id: int) -> list[Item]: ...  # ordered by position
    def update_item(self, item_id: int, title: str, url: str | None, image: str | None,
                    price_minor: int, note: str | None, really_want: bool, is_voucher: bool = False) -> None: ...
    def set_positions(self, ordered_item_ids: list[int]) -> None: ...
    def set_bought(self, item_id: int, at: datetime | None) -> None: ...
    def delete_item(self, item_id: int) -> None: ...
    def delete_all_items(self) -> None: ...
    def item_stats_by_person(self) -> list[tuple[int, int, int, int]]: ...  # (person_id, count, total_minor, sulk_count)
    def all_items(self) -> list[Item]: ...  # every item, any person -- for site-wide superlatives

    # item shares (a gift shared between two people in a household -- acts as
    # a normal gift for both)
    def add_item_share(self, item_id: int, person_id: int) -> None: ...
    def remove_item_share(self, item_id: int, person_id: int) -> None: ...
    def is_item_shared_with(self, item_id: int, person_id: int) -> bool: ...
    def people_sharing_item(self, item_id: int) -> list[Person]: ...
    def items_shared_with_person(self, person_id: int) -> list[Item]: ...

    # claims
    def claims_for_item(self, item_id: int) -> list[Claim]: ...
    def claims_by_user(self, user_id: int) -> list[Claim]: ...
    def add_claim(self, item_id: int, user_id: int, amount_minor: int, at: datetime) -> None: ...
    def set_claim_amount(self, item_id: int, user_id: int, amount_minor: int) -> None: ...
    def delete_claim(self, item_id: int, user_id: int) -> None: ...

    # notices
    def add_notice(self, user_id: int, kind: NoticeKind, params: dict, at: datetime) -> None: ...
    def notices_for_user(self, user_id: int) -> list[Notice]: ...
    def delete_notice(self, notice_id: int, user_id: int) -> None: ...
    def delete_all_notices(self) -> None: ...

    # activity (the site-wide notice board)
    def add_activity(self, kind: ActivityKind, household_id: int | None, person_id: int | None,
                     params: dict, at: datetime) -> None: ...
    def recent_activity(self, limit: int) -> list[Activity]: ...
    def activity_since(self, since_iso: str) -> list[Activity]: ...
    def delete_all_activity(self) -> None: ...
    def has_replied_recently(self, person_id: int, since_iso: str) -> bool: ...

    # settings
    def setting(self, key: str) -> str | None: ...
    def set_setting(self, key: str, value: str) -> None: ...

    # reveals (opt-in visibility of a household-mate's list on Everyone)
    def set_reveal(self, viewer_user_id: int, target_person_id: int, revealed: bool) -> None: ...
    def revealed_person_ids(self, viewer_user_id: int) -> set[int]: ...
    def is_revealed(self, viewer_user_id: int, target_person_id: int) -> bool: ...

    # gerry events (badges, logged whenever a real trigger condition fires)
    def add_gerry_event(self, user_id: int, trigger: str, at: datetime) -> None: ...
    def gerry_event_totals(self) -> list[tuple[int, str, int]]: ...  # (user_id, trigger, count)
    def delete_all_gerry_events(self) -> None: ...
